######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 12 13:08:01 2011
######################################################################

TEMPLATE = subdirs

  SUBDIRS = $$PWD/src \
            $$PWD/libs/qwt-6.2/qwt.pro




